path: data/yolo
train: train/images
val: val/images
test: test/images
nc: 32
names:
- tooth_01
- tooth_02
- tooth_03
- tooth_04
- tooth_05
- tooth_06
- tooth_07
- tooth_08
- tooth_09
- tooth_10
- tooth_11
- tooth_12
- tooth_13
- tooth_14
- tooth_15
- tooth_16
- tooth_17
- tooth_18
- tooth_19
- tooth_20
- tooth_21
- tooth_22
- tooth_23
- tooth_24
- tooth_25
- tooth_26
- tooth_27
- tooth_28
- tooth_29
- tooth_30
- tooth_31
- tooth_32
